import "./globals.css";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/footer";
import AuthWrapper from "@/components/wrapper/authWrapper";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BekuMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.className} antialiased`}>
        <AuthWrapper>{children}</AuthWrapper>
        <Toaster position="top-right" />
        <Footer />
      </body>
    </html>
  );
}
